#if !defined(AFX_ABOUTDLG_H)
#define AFX_ABOUTDLG_H

#include "StdAfx.h"
#include "compat.h"
#include "res/resource.h"

// VTABLE: CONFIG 0x00406308
// SIZE 0x60

/**
 * @brief [AI] Dialog for the application's About box. Inherits from CDialog.
 * @details [AI] This dialog provides information about the application, typically version and credits, accessed from the Help->About menu. It corresponds to the resource dialog IDD_ABOUT and has its own message map (though no custom messages are handled here). [AI]
 */
class CAboutDialog : public CDialog {
public:
	/**
	 * @brief [AI] Constructor. Initializes the about dialog using the dialog resource IDD_ABOUT.
	 * @details [AI] This sets up the CDialog base class with the ID for the about dialog resource template. [AI]
	 */
	CAboutDialog();

	/**
	 * @brief [AI] Dialog resource identifier.
	 * @details [AI] This enum value defines the ID used to identify the about dialog resource within the application. [AI]
	 */
	enum {
		IDD = IDD_ABOUT ///< [AI] Dialog resource ID (IDD_ABOUT) for the about dialog.
	};

protected:
	/**
	 * @brief [AI] Data exchange method for MFC dialog controls.
	 * @param pDX Pointer to the data exchange context. [AI]
	 * @details [AI] Handles data exchange and validation between UI controls and data members. Overridden from CDialog. [AI]
	 */
	void DoDataExchange(CDataExchange* pDX) override;

protected:
	/**
	 * @brief [AI] Declares the MFC message map for the About dialog.
	 * @details [AI] The DECLARE_MESSAGE_MAP macro is required for all classes that define a message map, even if no messages are handled directly here. [AI]
	 */
	DECLARE_MESSAGE_MAP()
};

// SYNTHETIC: CONFIG 0x00403cb0
// CAboutDialog::`scalar deleting destructor'
// @brief [AI] Scalar deleting destructor generated by the compiler for proper deletion of the dialog object. [AI]

// FUNCTION: CONFIG 0x00403d30
// CAboutDialog::_GetBaseMessageMap
// @brief [AI] Returns a pointer to the base message map structure for CAboutDialog, used internally by the MFC framework. [AI]

// FUNCTION: CONFIG 0x00403d40
// CAboutDialog::GetMessageMap
// @brief [AI] Returns the message map for this dialog; required for proper MFC message routing. [AI]

// GLOBAL: CONFIG 0x00406100
// CAboutDialog::messageMap
// @brief [AI] Static message map instance associated with CAboutDialog. [AI]

// GLOBAL: CONFIG 0x00406108
// CAboutDialog::_messageEntries
// @brief [AI] Static array of message map entries for CAboutDialog. [AI]

#endif // !defined(AFX_ABOUTDLG_H)
