// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef CARRACE_ACTIONS_H
#define CARRACE_ACTIONS_H

/**
 * @namespace CarraceScript [AI]
 * @brief [AI] Contains enumerations for script action identifiers used in the LEGO Island car race mini-game scripting system.
 * @details [AI] Every constant in the CarraceScript::Script enumeration corresponds to an object, media resource, variable, controller, or animation present or triggered in the LEGO Island Car Race SI script file. These IDs are used primarily for logic in scripting and engine-side lookups and dispatch. [AI]
 */
namespace CarraceScript
{
#if __cplusplus >= 201103L
	/**
	 * @enum Script [AI]
	 * @brief [AI] Enumerates all script objects, variable/action names, control widgets, actors, animations, sounds, and media assets present in the LEGO Island Car Race script file.
	 * @details [AI]
	 *  - The indices correspond directly to the SI file order: changing the order in the SI file will change these indices.
	 *  - The naming convention is designed to match the object, variable, animation, or sound present in the game script or to match bitmap/asset names where relevant.
	 *  - Negative values (e.g., c_noneCarrace) are used as error/sentinel values.
	 *  - Groupings are often consecutive (e.g., RaceCarDashboard images, RaceCar sound triggers, VO lines, animation triggers).
	 *  - These are essential for engine-side logic for referencing and dispatching script elements. [AI]
	 */
	enum Script : int {
#else
	/**
	 * @enum Script [AI]
	 * @brief [AI] Enumerates all script objects, variable/action names, control widgets, actors, animations, sounds, and media assets present in the LEGO Island Car Race script file.
	 * @details [AI]
	 *  - The indices correspond directly to the SI file order: changing the order in the SI file will change these indices.
	 *  - The naming convention is designed to match the object, variable, animation, or sound present in the game script or to match bitmap/asset names where relevant.
	 *  - Negative values (e.g., c_noneCarrace) are used as error/sentinel values.
	 *  - Groupings are often consecutive (e.g., RaceCarDashboard images, RaceCar sound triggers, VO lines, animation triggers).
	 *  - These are essential for engine-side logic for referencing and dispatching script elements. [AI]
	 */
	enum Script {
#endif
		c_noneCarrace = -1, ///< @brief [AI] Sentinel value used to indicate 'no valid action/object' in Carrace script context.

		c__CarRace_World = 0, ///< @brief [AI] Root node/world object for the Car Race script instance.
		c_SpeedMeter = 1, ///< @brief [AI] The speed meter user interface widget.
		c_FuelMeter = 2, ///< @brief [AI] The fuel meter user interface widget.
		c_Info_Ctl = 3, ///< @brief [AI] The info control widget shown in Car Race.
		c_DistanceMeter = 4, ///< @brief [AI] Distance meter user interface widget.
		c_Horn_Ctl = 5, ///< @brief [AI] Control widget for car horn.
		c_Horn_Up_Bitmap = 6, ///< @brief [AI] Bitmap asset for horn in 'up' or non-pressed state.
		c_Horn_Down = 7, ///< @brief [AI] Triggers horn 'down' logic (pressed).
		c_Horn_Sound = 8, ///< @brief [AI] Sound asset for car horn.
		c_Horn_Down_Bitmap = 9, ///< @brief [AI] Bitmap for horn when pressed down.
		c_UserCar_Actor = 10, ///< @brief [AI] Main user-controllable car actor in the race.
		c_Studs_Actor = 11, ///< @brief [AI] Actor representing Studs (NPC racer).
		c_Rhoda_Actor = 12, ///< @brief [AI] Actor representing Rhoda (NPC racer).
		c_irtx08ra_PlayWav = 13, ///< @brief [AI] Embedded script object to play a WAV sound, associated with the irtx08ra marker.
		c_Map_Ctl = 14, ///< @brief [AI] Map control widget for minimap or race overview.
		c_Map_Up_Bitmap = 15, ///< @brief [AI] Bitmap for map button in 'up'/idle state.
		c_Map_Down_Bitmap = 16, ///< @brief [AI] Bitmap for map button in 'down'/pressed state.
		c_Info_Up_Bitmap = 17, ///< @brief [AI] Bitmap for info button in 'up'/idle state.
		c_Info_Down_Bitmap = 18, ///< @brief [AI] Bitmap for info button in 'down'/pressed state.
		c_CarLocator2 = 19, ///< @brief [AI] Object that aids in car location/tracking (likely on minimap).
		c_CarLocator3 = 20, ///< @brief [AI] Secondary car locating/tracking object.
		c_StartTriggers = 21, ///< @brief [AI] Collection of triggers to start the race/event.
		c_RacePath = 22, ///< @brief [AI] Node representing the racing path/topology.
		c_HitWallSound = 23, ///< @brief [AI] Sound played on hitting a wall.
		c_SetHitWallSound = 24, ///< @brief [AI] Action/variable to assign the sound effect to wall collisions.
		c_HitActorSound = 25, ///< @brief [AI] Sound associated when hitting another actor.
		c_SetHitActorSound = 26, ///< @brief [AI] Action/variable to assign the sound effect for hitting actors.
		c_VO1 = 27, ///< @brief [AI] Voice-over audio line 1 (possibly commentary or instruction).
		c_VO2 = 28, ///< @brief [AI] Voice-over audio line 2.
		c_VO3 = 29, ///< @brief [AI] Voice-over audio line 3.
		c_VO4 = 30, ///< @brief [AI] Voice-over audio line 4.
		c_VO5 = 31, ///< @brief [AI] Voice-over audio line 5.
		c_VO6 = 32, ///< @brief [AI] Voice-over audio line 6.
		c_VO7 = 33, ///< @brief [AI] Voice-over audio line 7.
		c_VO8 = 34, ///< @brief [AI] Voice-over audio line 8.
		c_VO9 = 35, ///< @brief [AI] Voice-over audio line 9.
		c_VO10 = 36, ///< @brief [AI] Voice-over audio line 10.
		c_VO11 = 37, ///< @brief [AI] Voice-over audio line 11.
		c_VO12 = 38, ///< @brief [AI] Voice-over audio line 12.
		c_VO13 = 39, ///< @brief [AI] Voice-over audio line 13.
		c_VO14 = 40, ///< @brief [AI] Voice-over audio line 14.
		c_RaceCarDashboard11_Bitmap = 41, ///< @brief [AI] Bitmap for dashboard, car, slot 1-1.
		c_RaceCarDashboard12_Bitmap = 42, ///< @brief [AI] Bitmap for dashboard, car, slot 1-2.
		c_RaceCarDashboard13_Bitmap = 43, ///< @brief [AI] Bitmap for dashboard, car, slot 1-3.
		c_RaceCarDashboard14_Bitmap = 44, ///< @brief [AI] Bitmap for dashboard, car, slot 1-4.
		c_RaceCarDashboard15_Bitmap = 45, ///< @brief [AI] Bitmap for dashboard, car, slot 1-5.
		c_RaceCarDashboard16_Bitmap = 46, ///< @brief [AI] Bitmap for dashboard, car, slot 1-6.
		c_VO15 = 47, ///< @brief [AI] Voice-over audio line 15.
		c_VO16 = 48, ///< @brief [AI] Voice-over audio line 16.
		c_VO17 = 49, ///< @brief [AI] Voice-over audio line 17.
		c_VO18 = 50, ///< @brief [AI] Voice-over audio line 18.
		c_RaceCarDashboard21_Bitmap = 51, ///< @brief [AI] Bitmap for dashboard, car, slot 2-1.
		c_RaceCarDashboard22_Bitmap = 52, ///< @brief [AI] Bitmap for dashboard, car, slot 2-2.
		c_RaceCarDashboard23_Bitmap = 53, ///< @brief [AI] Bitmap for dashboard, car, slot 2-3.
		c_RaceCarDashboard24_Bitmap = 54, ///< @brief [AI] Bitmap for dashboard, car, slot 2-4.
		c_RaceCarDashboard25_Bitmap = 55, ///< @brief [AI] Bitmap for dashboard, car, slot 2-5.
		c_RaceCarDashboard26_Bitmap = 56, ///< @brief [AI] Bitmap for dashboard, car, slot 2-6.
		c_VO19 = 57, ///< @brief [AI] Voice-over audio line 19.
		c_VO20 = 58, ///< @brief [AI] Voice-over audio line 20.
		c_VO21 = 59, ///< @brief [AI] Voice-over audio line 21.
		c_SkelKick_Sound = 60, ///< @brief [AI] Sound played for skeleton kick event.
		c_RaceCarDashboard31_Bitmap = 61, ///< @brief [AI] Bitmap for dashboard, car, slot 3-1.
		c_RaceCarDashboard32_Bitmap = 62, ///< @brief [AI] Bitmap for dashboard, car, slot 3-2.
		c_RaceCarDashboard33_Bitmap = 63, ///< @brief [AI] Bitmap for dashboard, car, slot 3-3.
		c_RaceCarDashboard34_Bitmap = 64, ///< @brief [AI] Bitmap for dashboard, car, slot 3-4.
		c_RaceCarDashboard35_Bitmap = 65, ///< @brief [AI] Bitmap for dashboard, car, slot 3-5.
		c_RaceCarDashboard36_Bitmap = 66, ///< @brief [AI] Bitmap for dashboard, car, slot 3-6.
		c_Rhoda_Sound = 67, ///< @brief [AI] Sound asset associated with Rhoda.
		c_Rhoda_Locator = 68, ///< @brief [AI] Script variable/object for Rhoda's position.
		c_RcRhod00_Anim = 69, ///< @brief [AI] Animation for Rhoda (variant 00).
		c_RcRhod01_Anim = 70, ///< @brief [AI] Animation for Rhoda (variant 01).
		c_RaceCarDashboard41_Bitmap = 71, ///< @brief [AI] Bitmap for dashboard, car, slot 4-1.
		c_RaceCarDashboard42_Bitmap = 72, ///< @brief [AI] Bitmap for dashboard, car, slot 4-2.
		c_RaceCarDashboard43_Bitmap = 73, ///< @brief [AI] Bitmap for dashboard, car, slot 4-3.
		c_RaceCarDashboard44_Bitmap = 74, ///< @brief [AI] Bitmap for dashboard, car, slot 4-4.
		c_RaceCarDashboard45_Bitmap = 75, ///< @brief [AI] Bitmap for dashboard, car, slot 4-5.
		c_RaceCarDashboard46_Bitmap = 76, ///< @brief [AI] Bitmap for dashboard, car, slot 4-6.
		c_RcRhod02_Anim = 77, ///< @brief [AI] Animation for Rhoda (variant 02).
		c_RhodaCar_Actor = 78, ///< @brief [AI] Rhoda's car actor.
		c_RhodaCar_Model = 79, ///< @brief [AI] Model geometry for Rhoda's car.
		c_Rhoda_Model = 80, ///< @brief [AI] Model geometry for Rhoda.
		c_RaceCarDashboard51_Bitmap = 81, ///< @brief [AI] Bitmap for dashboard, car, slot 5-1.
		c_RaceCarDashboard52_Bitmap = 82, ///< @brief [AI] Bitmap for dashboard, car, slot 5-2.
		c_RaceCarDashboard53_Bitmap = 83, ///< @brief [AI] Bitmap for dashboard, car, slot 5-3.
		c_RaceCarDashboard54_Bitmap = 84, ///< @brief [AI] Bitmap for dashboard, car, slot 5-4.
		c_RaceCarDashboard55_Bitmap = 85, ///< @brief [AI] Bitmap for dashboard, car, slot 5-5.
		c_RaceCarDashboard56_Bitmap = 86, ///< @brief [AI] Bitmap for dashboard, car, slot 5-6.
		c_Studs_Sound = 87, ///< @brief [AI] Sound asset associated with Studs actor.
		c_Studs_Locator = 88, ///< @brief [AI] Script variable/object for Studs' position.
		c_RcStud00_Anim = 89, ///< @brief [AI] Animation for Studs (variant 00).
		c_RcStud01_Anim = 90, ///< @brief [AI] Animation for Studs (variant 01).
		c_RaceCarDashboard61_Bitmap = 91, ///< @brief [AI] Bitmap for dashboard, car, slot 6-1.
		c_RaceCarDashboard62_Bitmap = 92, ///< @brief [AI] Bitmap for dashboard, car, slot 6-2.
		c_RaceCarDashboard63_Bitmap = 93, ///< @brief [AI] Bitmap for dashboard, car, slot 6-3.
		c_RaceCarDashboard64_Bitmap = 94, ///< @brief [AI] Bitmap for dashboard, car, slot 6-4.
		c_RaceCarDashboard65_Bitmap = 95, ///< @brief [AI] Bitmap for dashboard, car, slot 6-5.
		c_RaceCarDashboard66_Bitmap = 96, ///< @brief [AI] Bitmap for dashboard, car, slot 6-6.
		c_RaceCarDashboard = 97, ///< @brief [AI] General dashboard for race car.
		c_RaceCarArms_Ctl = 98, ///< @brief [AI] Racecar arms control (dashboard animation).
		c_RcStud02_Anim = 99, ///< @brief [AI] Animation for Studs (variant 02).
		c_StudsCar_Actor = 100, ///< @brief [AI] Studs' car actor.
		c_StudsCar_Model = 101, ///< @brief [AI] Model geometry for Studs' car.
		c_Studs_Model = 102, ///< @brief [AI] Model geometry for Studs.
		c_SkelKick1_Anim = 103, ///< @brief [AI] Skeleton kick animation, variant 1.
		c_SkelKick2_Anim = 104, ///< @brief [AI] Skeleton kick animation, variant 2.
		c_User_Locator = 105, ///< @brief [AI] Script variable/object for user actor/car location.
		c_UserCar_Model = 106, ///< @brief [AI] Model geometry for the user's car.
		c_ScaryRun_Sound = 107, ///< @brief [AI] Sound asset for 'scary run' event.
		c_ScaryRun_Anim = 108, ///< @brief [AI] Animation for 'scary run' event.
		c_Skeleton_Actor = 109, ///< @brief [AI] Skeleton NPC actor in the car race.
		c_Skeleton_Model = 110, ///< @brief [AI] Model geometry for skeleton character.
		c_Ghost_Sound = 111, ///< @brief [AI] Sound effect for ghost character.
		c_Ghost_Anim = 112, ///< @brief [AI] Animation for ghost character.
		c_Ghost_Actor = 113, ///< @brief [AI] Ghost NPC actor in the car race.
		c_Ghost_Model = 114, ///< @brief [AI] Model geometry for ghost character.
		c_TireGuy_Anim = 115, ///< @brief [AI] Animation for TireGuy (pit crew/track hazard).
		c_TireGuy_Actor = 116, ///< @brief [AI] TireGuy actor instance in Car Race.
		c_TireGuy_Model = 117, ///< @brief [AI] Model geometry for TireGuy.
		c_Skelton1_Sound = 118, ///< @brief [AI] Sound for the first skeleton event.
		c_SJump_Anim = 119, ///< @brief [AI] Skeleton jump animation.
		c_Skelton1_Actor = 120, ///< @brief [AI] First skeleton actor.
		c_Skelton1_Model = 121, ///< @brief [AI] Model for first skeleton.
		c_SkelBig_Anim = 122, ///< @brief [AI] Big skeleton animation.
		c_SkelBig_Actor = 123, ///< @brief [AI] Big skeleton actor instance.
		c_SkelBig_Model = 124, ///< @brief [AI] Model geometry for big skeleton character.
		c_DorA_Actor = 125, ///< @brief [AI] Door A actor for race track events.
		c_DorA_Model = 126, ///< @brief [AI] 3D model for Door A.
		c_DorB_Actor = 127, ///< @brief [AI] Door B actor for race track events.
		c_DorB_Model = 128, ///< @brief [AI] 3D model for Door B.
		c_DorC_Actor = 129, ///< @brief [AI] Door C actor for race track events.
		c_DorC_Model = 130, ///< @brief [AI] 3D model for Door C.
		c_DorD_Actor = 131, ///< @brief [AI] Door D actor for race track events.
		c_DorD_Model = 132, ///< @brief [AI] 3D model for Door D.
		c_DorE_Actor = 133, ///< @brief [AI] Door E actor for race track events.
		c_DorE_Model = 134, ///< @brief [AI] 3D model for Door E.
		c_DorF_Actor = 135, ///< @brief [AI] Door F actor for race track events.
		c_DorF_Model = 136, ///< @brief [AI] 3D model for Door F.
		c_DorG_Actor = 137, ///< @brief [AI] Door G actor for race track events.
		c_DorG_Model = 138, ///< @brief [AI] 3D model for Door G.
		c_DorH_Actor = 139, ///< @brief [AI] Door H actor for race track events.
		c_DorH_Model = 140, ///< @brief [AI] 3D model for Door H.
		c_DorI_Actor = 141, ///< @brief [AI] Door I actor for race track events.
		c_DorI_Model = 142, ///< @brief [AI] 3D model for Door I.
		c_DorJ_Actor = 143, ///< @brief [AI] Door J actor for race track events.
		c_DorJ_Model = 144, ///< @brief [AI] 3D model for Door J.
		c_HideAni_Anim = 145, ///< @brief [AI] Animation to hide an element or actor.
		c_RaceCarArms_Mask_Bitmap = 146, ///< @brief [AI] Bitmap mask for racecar arms dashboard animation.
		c_srt001rh_Wav_500 = 147, ///< @brief [AI] WAV asset for SRT001RH dialog/audio 500.
		c_srt001rh_Pho_500 = 148, ///< @brief [AI] PHO phoneme data for SRT001RH 500.
		c_srt001rh_0_sfx = 149, ///< @brief [AI] First SFX for SRT001RH.
		c_srt001rh_1_sfx = 150, ///< @brief [AI] Second SFX for SRT001RH.
		c_srt001rh_2_sfx = 151, ///< @brief [AI] Third SFX for SRT001RH.
		c_srt001rh_Anim = 152, ///< @brief [AI] Animation associated with SRT001RH line 500.
		c_SRT001SL_Wav_501 = 153, ///< @brief [AI] WAV asset for SRT001SL dialog/audio 501.
		c_SRT001SL_Pho_501 = 154, ///< @brief [AI] PHO phoneme data for SRT001SL 501.
		c_srt001sl_0_sfx = 155, ///< @brief [AI] SFX asset 0 for SRT001SL.
		c_srt001sl_1_sfx = 156, ///< @brief [AI] SFX asset 1 for SRT001SL.
		c_srt001sl_2_sfx = 157, ///< @brief [AI] SFX asset 2 for SRT001SL.
		c_srt001sl_3_sfx = 158, ///< @brief [AI] SFX asset 3 for SRT001SL.
		c_srt001sl_4_sfx = 159, ///< @brief [AI] SFX asset 4 for SRT001SL.
		c_srt001sl_Anim = 160, ///< @brief [AI] Animation associated with SRT001SL line 501.
		c_srt002rh_Wav_502 = 161, ///< @brief [AI] WAV asset for SRT002RH dialog/audio 502.
		c_srt002rh_Pho_502 = 162, ///< @brief [AI] PHO phoneme data for SRT002RH 502.
		c_srt002rh_0_sfx = 163, ///< @brief [AI] SFX asset 0 for SRT002RH.
		c_srt002rh_1_sfx = 164, ///< @brief [AI] SFX asset 1 for SRT002RH.
		c_srt002rh_2_sfx = 165, ///< @brief [AI] SFX asset 2 for SRT002RH.
		c_srt002rh_Anim = 166, ///< @brief [AI] Animation associated with SRT002RH line 502.
		c_SRT002SL_Wav_503 = 167, ///< @brief [AI] WAV asset for SRT002SL dialog/audio 503.
		c_SRT002SL_Pho_503 = 168, ///< @brief [AI] PHO phoneme data for SRT002SL 503.
		c_srt002sl_0_sfx = 169, ///< @brief [AI] SFX asset 0 for SRT002SL.
		c_srt002sl_1_sfx = 170, ///< @brief [AI] SFX asset 1 for SRT002SL.
		c_srt002sl_2_sfx = 171, ///< @brief [AI] SFX asset 2 for SRT002SL.
		c_srt002sl_3_sfx = 172, ///< @brief [AI] SFX asset 3 for SRT002SL.
		c_srt002sl_Anim = 173, ///< @brief [AI] Animation associated with SRT002SL line 503.
		c_srt003rh_Wav_504 = 174, ///< @brief [AI] WAV asset for SRT003RH dialog/audio 504.
		c_srt003rh_Pho_504 = 175, ///< @brief [AI] PHO phoneme data for SRT003RH 504.
		c_srt003rh_0_sfx = 176, ///< @brief [AI] SFX asset 0 for SRT003RH.
		c_srt003rh_1_sfx = 177, ///< @brief [AI] SFX asset 1 for SRT003RH.
		c_srt003rh_Anim = 178, ///< @brief [AI] Animation associated with SRT003RH line 504.
		c_SRT003SL_Wav_505 = 179, ///< @brief [AI] WAV asset for SRT003SL dialog/audio 505.
		c_SRT003SL_Pho_505 = 180, ///< @brief [AI] PHO phoneme data for SRT003SL 505.
		c_srt003sl_0_sfx = 181, ///< @brief [AI] SFX asset 0 for SRT003SL.
		c_srt003sl_1_sfx = 182, ///< @brief [AI] SFX asset 1 for SRT003SL.
		c_srt003sl_Anim = 183, ///< @brief [AI] Animation associated with SRT003SL line 505.
		c_SRT004SL_Wav_506 = 184, ///< @brief [AI] WAV asset for SRT004SL dialog/audio 506.
		c_SRT004SL_Pho_506 = 185, ///< @brief [AI] PHO phoneme data for SRT004SL 506.
		c_srt004sl_0_sfx = 186, ///< @brief [AI] SFX asset 0 for SRT004SL.
		c_srt004sl_1_sfx = 187, ///< @brief [AI] SFX asset 1 for SRT004SL.
		c_srt004sl_2_sfx = 188, ///< @brief [AI] SFX asset 2 for SRT004SL.
		c_srt004sl_Anim = 189, ///< @brief [AI] Animation associated with SRT004SL line 506.
		c_srt005sl_Wav_507 = 190, ///< @brief [AI] WAV asset for SRT005SL dialog/audio 507.
		c_srt005sl_Pho_507 = 191, ///< @brief [AI] PHO phoneme data for SRT005SL 507.
		c_srt005sl_0_sfx = 192, ///< @brief [AI] SFX asset 0 for SRT005SL.
		c_srt005sl_1_sfx = 193, ///< @brief [AI] SFX asset 1 for SRT005SL.
		c_srt005sl_2_sfx = 194, ///< @brief [AI] SFX asset 2 for SRT005SL.
		c_srt005sl_3_sfx = 195, ///< @brief [AI] SFX asset 3 for SRT005SL.
		c_srt005sl_Anim = 196, ///< @brief [AI] Animation associated with SRT005SL line 507.
		c_IRTX08RA_Wav_508 = 197, ///< @brief [AI] WAV asset for IRTX08RA event 508.
		c_nrtflag0_Anim = 198, ///< @brief [AI] Animation for NRT Flag 0 event.
		c_SRT007RH_Wav_509 = 199, ///< @brief [AI] WAV asset for SRT007RH dialog/audio 509.
		c_SRT007RH_Pho_509 = 200, ///< @brief [AI] PHO phoneme data for SRT007RH 509.
		c_srt007rh_0_sfx = 201, ///< @brief [AI] SFX asset 0 for SRT007RH.
		c_srt007rh_1_sfx = 202, ///< @brief [AI] SFX asset 1 for SRT007RH.
		c_srt007rh_2_sfx = 203, ///< @brief [AI] SFX asset 2 for SRT007RH.
		c_srt007rh_3_sfx = 204, ///< @brief [AI] SFX asset 3 for SRT007RH.
		c_srt007rh_Anim = 205, ///< @brief [AI] Animation associated with SRT007RH line 509.
		c_SRT008RH_Wav_510 = 206, ///< @brief [AI] WAV asset for SRT008RH dialog/audio 510.
		c_SRT008RH_Pho_510 = 207, ///< @brief [AI] PHO phoneme data for SRT008RH 510.
		c_srt008rh_0_sfx = 208, ///< @brief [AI] SFX asset 0 for SRT008RH.
		c_srt008rh_1_sfx = 209, ///< @brief [AI] SFX asset 1 for SRT008RH.
		c_srt008rh_2_sfx = 210, ///< @brief [AI] SFX asset 2 for SRT008RH.
		c_srt008rh_3_sfx = 211, ///< @brief [AI] SFX asset 3 for SRT008RH.
		c_srt008rh_Anim = 212, ///< @brief [AI] Animation associated with SRT008RH line 510.
		c_SRT009RH_Wav_511 = 213, ///< @brief [AI] WAV asset for SRT009RH dialog/audio 511.
		c_SRT009RH_Pho_511 = 214, ///< @brief [AI] PHO phoneme data for SRT009RH 511.
		c_srt009rh_0_sfx = 215, ///< @brief [AI] SFX asset 0 for SRT009RH.
		c_srt009rh_1_sfx = 216, ///< @brief [AI] SFX asset 1 for SRT009RH.
		c_srt009rh_2_sfx = 217, ///< @brief [AI] SFX asset 2 for SRT009RH.
		c_srt009rh_3_sfx = 218, ///< @brief [AI] SFX asset 3 for SRT009RH.
		c_srt009rh_Anim = 219, ///< @brief [AI] Animation associated with SRT009RH line 511.
		c_SRT010RH_Wav_512 = 220, ///< @brief [AI] WAV asset for SRT010RH dialog/audio 512.
		c_SRT010RH_Pho_512 = 221, ///< @brief [AI] PHO phoneme data for SRT010RH 512.
		c_srt010rh_0_sfx = 222, ///< @brief [AI] SFX asset 0 for SRT010RH.
		c_srt010rh_1_sfx = 223, ///< @brief [AI] SFX asset 1 for SRT010RH.
		c_srt010rh_2_sfx = 224, ///< @brief [AI] SFX asset 2 for SRT010RH.
		c_srt010rh_Anim = 225, ///< @brief [AI] Animation associated with SRT010RH line 512.
		c_SRT011RH_Wav_513 = 226, ///< @brief [AI] WAV asset for SRT011RH dialog/audio 513.
		c_SRT011RH_Pho_513 = 227, ///< @brief [AI] PHO phoneme data for SRT011RH 513.
		c_srt011rh_0_sfx = 228, ///< @brief [AI] SFX asset 0 for SRT011RH.
		c_srt011rh_1_sfx = 229, ///< @brief [AI] SFX asset 1 for SRT011RH.
		c_srt011rh_2_sfx = 230, ///< @brief [AI] SFX asset 2 for SRT011RH.
		c_srt011rh_3_sfx = 231, ///< @brief [AI] SFX asset 3 for SRT011RH.
		c_srt011rh_Anim = 232, ///< @brief [AI] Animation associated with SRT011RH line 513.
		c_SRT011SL_Wav_514 = 233, ///< @brief [AI] WAV asset for SRT011SL dialog/audio 514.
		c_SRT011SL_Pho_514 = 234, ///< @brief [AI] PHO phoneme data for SRT011SL 514.
		c_srt011sl_0_sfx = 235, ///< @brief [AI] SFX asset 0 for SRT011SL.
		c_srt011sl_1_sfx = 236, ///< @brief [AI] SFX asset 1 for SRT011SL.
		c_srt011sl_2_sfx = 237, ///< @brief [AI] SFX asset 2 for SRT011SL.
		c_srt011sl_3_sfx = 238, ///< @brief [AI] SFX asset 3 for SRT011SL.
		c_srt011sl_Anim = 239, ///< @brief [AI] Animation associated with SRT011SL line 514.
		c_SRT012RH_Wav_515 = 240, ///< @brief [AI] WAV asset for SRT012RH dialog/audio 515.
		c_SRT012RH_Pho_515 = 241, ///< @brief [AI] PHO phoneme data for SRT012RH 515.
		c_srt012rh_0_sfx = 242, ///< @brief [AI] SFX asset 0 for SRT012RH.
		c_srt012rh_1_sfx = 243, ///< @brief [AI] SFX asset 1 for SRT012RH.
		c_srt012rh_2_sfx = 244, ///< @brief [AI] SFX asset 2 for SRT012RH.
		c_srt012rh_3_sfx = 245, ///< @brief [AI] SFX asset 3 for SRT012RH.
		c_srt012rh_Anim = 246, ///< @brief [AI] Animation associated with SRT012RH line 515.
		c_SRT012SL_Wav_516 = 247, ///< @brief [AI] WAV asset for SRT012SL dialog/audio 516.
		c_SRT012SL_Pho_516 = 248, ///< @brief [AI] PHO phoneme data for SRT012SL 516.
		c_srt012sl_0_sfx = 249, ///< @brief [AI] SFX asset 0 for SRT012SL.
		c_srt012sl_1_sfx = 250, ///< @brief [AI] SFX asset 1 for SRT012SL.
		c_srt012sl_2_sfx = 251, ///< @brief [AI] SFX asset 2 for SRT012SL.
		c_srt012sl_3_sfx = 252, ///< @brief [AI] SFX asset 3 for SRT012SL.
		c_srt012sl_Anim = 253, ///< @brief [AI] Animation associated with SRT012SL line 516.
		c_SRT013SL_Wav_517 = 254, ///< @brief [AI] WAV asset for SRT013SL dialog/audio 517.
		c_SRT013SL_Pho_517 = 255, ///< @brief [AI] PHO phoneme data for SRT013SL 517.
		c_srt013sl_0_sfx = 256, ///< @brief [AI] SFX asset 0 for SRT013SL.
		c_srt013sl_1_sfx = 257, ///< @brief [AI] SFX asset 1 for SRT013SL.
		c_srt013sl_2_sfx = 258, ///< @brief [AI] SFX asset 2 for SRT013SL.
		c_srt013sl_3_sfx = 259, ///< @brief [AI] SFX asset 3 for SRT013SL.
		c_srt013sl_Anim = 260, ///< @brief [AI] Animation associated with SRT013SL line 517.
		c_SRT014SL_Wav_518 = 261, ///< @brief [AI] WAV asset for SRT014SL dialog/audio 518.
		c_SRT014SL_Pho_518 = 262, ///< @brief [AI] PHO phoneme data for SRT014SL 518.
		c_srt014sl_0_sfx = 263, ///< @brief [AI] SFX asset 0 for SRT014SL.
		c_srt014sl_1_sfx = 264, ///< @brief [AI] SFX asset 1 for SRT014SL.
		c_srt014sl_2_sfx = 265, ///< @brief [AI] SFX asset 2 for SRT014SL.
		c_srt014sl_3_sfx = 266, ///< @brief [AI] SFX asset 3 for SRT014SL.
		c_srt014sl_4_sfx = 267, ///< @brief [AI] SFX asset 4 for SRT014SL.
		c_srt014sl_Anim = 268, ///< @brief [AI] Animation associated with SRT014SL line 518.
		c_SRT015SL_Wav_519 = 269, ///< @brief [AI] WAV asset for SRT015SL dialog/audio 519.
		c_SRT015SL_Pho_519 = 270, ///< @brief [AI] PHO phoneme data for SRT015SL 519.
		c_srt015sl_0_sfx = 271, ///< @brief [AI] SFX asset 0 for SRT015SL.
		c_srt015sl_1_sfx = 272, ///< @brief [AI] SFX asset 1 for SRT015SL.
		c_srt015sl_2_sfx = 273, ///< @brief [AI] SFX asset 2 for SRT015SL.
		c_srt015sl_3_sfx = 274, ///< @brief [AI] SFX asset 3 for SRT015SL.
		c_srt015sl_Anim = 275, ///< @brief [AI] Animation associated with SRT015SL line 519.
		c_SRT016SL_Wav_520 = 276, ///< @brief [AI] WAV asset for SRT016SL dialog/audio 520.
		c_SRT016SL_Pho_520 = 277, ///< @brief [AI] PHO phoneme data for SRT016SL 520.
		c_srt016sl_0_sfx = 278, ///< @brief [AI] SFX asset 0 for SRT016SL.
		c_srt016sl_1_sfx = 279, ///< @brief [AI] SFX asset 1 for SRT016SL.
		c_srt016sl_2_sfx = 280, ///< @brief [AI] SFX asset 2 for SRT016SL.
		c_srt016sl_3_sfx = 281, ///< @brief [AI] SFX asset 3 for SRT016SL.
		c_srt016sl_4_sfx = 282, ///< @brief [AI] SFX asset 4 for SRT016SL.
		c_srt016sl_Anim = 283, ///< @brief [AI] Animation associated with SRT016SL line 520.
		c_SRT017SL_Wav_521 = 284, ///< @brief [AI] WAV asset for SRT017SL dialog/audio 521.
		c_SRT017SL_Pho_521 = 285, ///< @brief [AI] PHO phoneme data for SRT017SL 521.
		c_srt017sl_0_sfx = 286, ///< @brief [AI] SFX asset 0 for SRT017SL.
		c_srt017sl_1_sfx = 287, ///< @brief [AI] SFX asset 1 for SRT017SL.
		c_srt017sl_2_sfx = 288, ///< @brief [AI] SFX asset 2 for SRT017SL.
		c_srt017sl_3_sfx = 289, ///< @brief [AI] SFX asset 3 for SRT017SL.
		c_srt017sl_Anim = 290, ///< @brief [AI] Animation associated with SRT017SL line 521.
		c_nrtrhod0_Anim = 291, ///< @brief [AI] Animation for NRT Rhoda 0 event.
		c_nrt001pz_Anim = 292, ///< @brief [AI] Animation for NRT, file 001 PZ event.
		c_nrt002pz_Anim = 293, ///< @brief [AI] Animation for NRT, file 002 PZ event.
		c_nrt003sh_Anim = 294, ///< @brief [AI] Animation for NRT, file 003 SH event.
		c_nrt004sh_Anim = 295, ///< @brief [AI] Animation for NRT, file 004 SH event.
		c_nrt005ft_Anim = 296, ///< @brief [AI] Animation for NRT, file 005 FT event.
		c_nrt008oc_Anim = 297, ///< @brief [AI] Animation for NRT, file 008 OC event.
		c_nrt010pz_Anim = 298, ///< @brief [AI] Animation for NRT, file 010 PZ event.
		c_nrt011pz_Anim = 299, ///< @brief [AI] Animation for NRT, file 011 PZ event.
		c_nrt012sl_Anim = 300, ///< @brief [AI] Animation for NRT, file 012 SL event.
		c_nrt013sl_Anim = 301, ///< @brief [AI] Animation for NRT, file 013 SL event.
		c_nrt014sl_Anim = 302, ///< @brief [AI] Animation for NRT, file 014 SL event.
		c_nrt015gh_Anim = 303, ///< @brief [AI] Animation for NRT, file 015 GH event.
		c_nrt015sl_Anim = 304, ///< @brief [AI] Animation for NRT, file 015 SL event.
		c_nrt016gh_Anim = 305, ///< @brief [AI] Animation for NRT, file 016 GH event.
		c_nrt017rc_Anim = 306, ///< @brief [AI] Animation for NRT, file 017 RC event.
		c_nrt018rc_Anim = 307, ///< @brief [AI] Animation for NRT, file 018 RC event.
		c_nrt020a1_Anim = 308, ///< @brief [AI] Animation for NRT, file 020 A1 event.
		c_nrt022sp_Anim = 309, ///< @brief [AI] Animation for NRT, file 022 SP event.
		c_nrt023sk_Anim = 310, ///< @brief [AI] Animation for NRT, file 023 SK event.
		c_nrt024a2_Anim = 311, ///< @brief [AI] Animation for NRT, file 024 A2 event.
		c_nrt025sw_Anim = 312, ///< @brief [AI] Animation for NRT, file 025 SW event.
		c_nrt026sw_Anim = 313, ///< @brief [AI] Animation for NRT, file 026 SW event.
		c_nrt027sw_Anim = 314, ///< @brief [AI] Animation for NRT, file 027 SW event.
		c_nrt028sw_Anim = 315, ///< @brief [AI] Animation for NRT, file 028 SW event.
		c_nrt029sw_Anim = 316, ///< @brief [AI] Animation for NRT, file 029 SW event.
		c_nrt030bk_Anim = 317, ///< @brief [AI] Animation for NRT, file 030 BK event.
		c_nrt031bk_Anim = 318, ///< @brief [AI] Animation for NRT, file 031 BK event.
		c_nrt032bk_Anim = 319, ///< @brief [AI] Animation for NRT, file 032 BK event.
		c_nrt033bk_Anim = 320, ///< @brief [AI] Animation for NRT, file 033 BK event.
		c_nrt034bk_Anim = 321, ///< @brief [AI] Animation for NRT, file 034 BK event.
		c_nrt035bk_Anim = 322, ///< @brief [AI] Animation for NRT, file 035 BK event.
		c_nrtrhod1_Anim = 323, ///< @brief [AI] Animation for NRT Rhoda 1 event.
		c_nrtrhod2_Anim = 324, ///< @brief [AI] Animation for NRT Rhoda 2 event.
		c_nrtrhod3_Anim = 325, ///< @brief [AI] Animation for NRT Rhoda 3 event.
		c_nrtstud0_Anim = 326, ///< @brief [AI] Animation for NRT Studs 0 event.
		c_nrtstud1_Anim = 327, ///< @brief [AI] Animation for NRT Studs 1 event.
		c_nrtstud2_Anim = 328, ///< @brief [AI] Animation for NRT Studs 2 event.
		c_nrtstud3_Anim = 329, ///< @brief [AI] Animation for NRT Studs 3 event.

		// RunAnim actions for SRT and NRT events [AI]
		c_srt001rh_RunAnim = 500, ///< @brief [AI] Action to run animation for SRT001RH.
		c_srt001sl_RunAnim = 501, ///< @brief [AI] Action to run animation for SRT001SL.
		c_srt002rh_RunAnim = 502, ///< @brief [AI] Action to run animation for SRT002RH.
		c_srt002sl_RunAnim = 503, ///< @brief [AI] Action to run animation for SRT002SL.
		c_srt003rh_RunAnim = 504, ///< @brief [AI] Action to run animation for SRT003RH.
		c_srt003sl_RunAnim = 505, ///< @brief [AI] Action to run animation for SRT003SL.
		c_srt004sl_RunAnim = 506, ///< @brief [AI] Action to run animation for SRT004SL.
		c_srt005sl_RunAnim = 507, ///< @brief [AI] Action to run animation for SRT005SL.
		c_nrtflag0_RunAnim = 508, ///< @brief [AI] Action to run animation for NRTFLAG0.
		c_srt007rh_RunAnim = 509, ///< @brief [AI] Action to run animation for SRT007RH.
		c_srt008rh_RunAnim = 510, ///< @brief [AI] Action to run animation for SRT008RH.
		c_srt009rh_RunAnim = 511, ///< @brief [AI] Action to run animation for SRT009RH.
		c_srt010rh_RunAnim = 512, ///< @brief [AI] Action to run animation for SRT010RH.
		c_srt011rh_RunAnim = 513, ///< @brief [AI] Action to run animation for SRT011RH.
		c_srt011sl_RunAnim = 514, ///< @brief [AI] Action to run animation for SRT011SL.
		c_srt012rh_RunAnim = 515, ///< @brief [AI] Action to run animation for SRT012RH.
		c_srt012sl_RunAnim = 516, ///< @brief [AI] Action to run animation for SRT012SL.
		c_srt013sl_RunAnim = 517, ///< @brief [AI] Action to run animation for SRT013SL.
		c_srt014sl_RunAnim = 518, ///< @brief [AI] Action to run animation for SRT014SL.
		c_srt015sl_RunAnim = 519, ///< @brief [AI] Action to run animation for SRT015SL.
		c_srt016sl_RunAnim = 520, ///< @brief [AI] Action to run animation for SRT016SL.
		c_srt017sl_RunAnim = 521, ///< @brief [AI] Action to run animation for SRT017SL.
		c_nrtrhod0_RunAnim = 522, ///< @brief [AI] Action to run animation for NRTRhod0.
		c_nrt001pz_RunAnim = 523, ///< @brief [AI] Action to run animation for NRT001PZ.
		c_nrt002pz_RunAnim = 524, ///< @brief [AI] Action to run animation for NRT002PZ.
		c_nrt003sh_RunAnim = 525, ///< @brief [AI] Action to run animation for NRT003SH.
		c_nrt004sh_RunAnim = 526, ///< @brief [AI] Action to run animation for NRT004SH.
		c_nrt005ft_RunAnim = 527, ///< @brief [AI] Action to run animation for NRT005FT.
		c_nrt008oc_RunAnim = 528, ///< @brief [AI] Action to run animation for NRT008OC.
		c_nrt010pz_RunAnim = 529, ///< @brief [AI] Action to run animation for NRT010PZ.
		c_nrt011pz_RunAnim = 530, ///< @brief [AI] Action to run animation for NRT011PZ.
		c_nrt012sl_RunAnim = 531, ///< @brief [AI] Action to run animation for NRT012SL.
		c_nrt013sl_RunAnim = 532, ///< @brief [AI] Action to run animation for NRT013SL.
		c_nrt014sl_RunAnim = 533, ///< @brief [AI] Action to run animation for NRT014SL.
		c_nrt015gh_RunAnim = 534, ///< @brief [AI] Action to run animation for NRT015GH.
		c_nrt015sl_RunAnim = 535, ///< @brief [AI] Action to run animation for NRT015SL.
		c_nrt016gh_RunAnim = 536, ///< @brief [AI] Action to run animation for NRT016GH.
		c_nrt017rc_RunAnim = 537, ///< @brief [AI] Action to run animation for NRT017RC.
		c_nrt018rc_RunAnim = 538, ///< @brief [AI] Action to run animation for NRT018RC.
		c_nrt020a1_RunAnim = 539, ///< @brief [AI] Action to run animation for NRT020A1.
		c_nrt022sp_RunAnim = 540, ///< @brief [AI] Action to run animation for NRT022SP.
		c_nrt023sk_RunAnim = 541, ///< @brief [AI] Action to run animation for NRT023SK.
		c_nrt024a2_RunAnim = 542, ///< @brief [AI] Action to run animation for NRT024A2.
		c_nrt025sw_RunAnim = 543, ///< @brief [AI] Action to run animation for NRT025SW.
		c_nrt026sw_RunAnim = 544, ///< @brief [AI] Action to run animation for NRT026SW.
		c_nrt027sw_RunAnim = 545, ///< @brief [AI] Action to run animation for NRT027SW.
		c_nrt028sw_RunAnim = 546, ///< @brief [AI] Action to run animation for NRT028SW.
		c_nrt029sw_RunAnim = 547, ///< @brief [AI] Action to run animation for NRT029SW.
		c_nrt030bk_RunAnim = 548, ///< @brief [AI] Action to run animation for NRT030BK.
		c_nrt031bk_RunAnim = 549, ///< @brief [AI] Action to run animation for NRT031BK.
		c_nrt032bk_RunAnim = 550, ///< @brief [AI] Action to run animation for NRT032BK.
		c_nrt033bk_RunAnim = 551, ///< @brief [AI] Action to run animation for NRT033BK.
		c_nrt034bk_RunAnim = 552, ///< @brief [AI] Action to run animation for NRT034BK.
		c_nrt035bk_RunAnim = 553, ///< @brief [AI] Action to run animation for NRT035BK.
		c_nrtrhod1_RunAnim = 554, ///< @brief [AI] Action to run animation for NRTRhod1.
		c_nrtrhod2_RunAnim = 555, ///< @brief [AI] Action to run animation for NRTRhod2.
		c_nrtrhod3_RunAnim = 556, ///< @brief [AI] Action to run animation for NRTRhod3.
		c_nrtstud0_RunAnim = 557, ///< @brief [AI] Action to run animation for NRTStud0.
		c_nrtstud1_RunAnim = 558, ///< @brief [AI] Action to run animation for NRTStud1.
		c_nrtstud2_RunAnim = 559, ///< @brief [AI] Action to run animation for NRTStud2.
		c_nrtstud3_RunAnim = 560  ///< @brief [AI] Action to run animation for NRTStud3.
	};
} // namespace CarraceScript

#endif // CARRACE_ACTIONS_H
