// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef DUNECAR_ACTIONS_H
#define DUNECAR_ACTIONS_H

/**
 * @namespace DunecarScript
 * @brief [AI] Namespace containing enums for identifying and referencing specific script actions and entities for the Dune Car mini-game.
 * @details [AI] This namespace is used for strongly-typed enumeration values representing all the elements, actions, sounds, bitmaps, and other resources
 *              used by the Dune Car (Dune Buggy) construction/painting/minigame in LEGO Island. The enum values map various script, model, control,
 *              bitmap, sound, and animation resource nodes by their unique identifiers.
 */
namespace DunecarScript
{
#if __cplusplus >= 201103L
/**
 * @enum Script
 * @brief [AI] Strongly-typed enum for all known script actions, controls, media, and other resource references in the Dune Car module.
 * @details [AI] Generated automatically, this enum is intended for dispatch and identification of scriptable resources in the Dune Car module,
 *              including UI controls, color selections, sound triggers, animation identifiers, and bitmaps. Enum constants are typically used
 *              as object IDs or command IDs in the Dune Car script interpreter and resource framework.
 */
enum Script : int {
#else
/**
 * @enum Script
 * @brief [AI] Enum for all known script actions, controls, media, and other resource references in the Dune Car module (non-C++11 variant).
 * @details [AI] See above.
 */
enum Script {
#endif
	c_noneDunecar = -1,                ///< [AI] Sentinel value for no action or invalid ID.

	c__StartUp = 0,                    ///< [AI] Startup or initial script event.

	c_DuneBugy_Actor = 2,              ///< [AI] ID for the main Dune Buggy actor instance.

	c_Info_Ctl = 5,                    ///< [AI] Control for Info-related UI action.
	c_Exit_Ctl = 6,                    ///< [AI] Control for Exit UI action.
	c_ShelfUp_Ctl = 7,                 ///< [AI] Control for shelf-up (likely select or open shelf).
	c_Platform_Ctl = 8,                ///< [AI] Control for platform (object manipulating the car's platform).

	c_DuneBugy_Model = 64,             ///< [AI] Model resource for the Dune Buggy itself.
	c_Background = 65,                 ///< [AI] Background image/resource.
	c_ColorBook_Bitmap = 66,           ///< [AI] Color selection bitmap(s).
	c_ShelfUp_Up_Bitmap = 67,          ///< [AI] Bitmap for shelf "up" (pressed/highlighted).
	c_ShelfUp_Down_Bitmap = 68,        ///< [AI] Bitmap for shelf "down"/deselected.
	c_PlatformUp_Bitmap = 69,          ///< [AI] Bitmap for platform "up" state.
	c_PlatformLeft = 70,               ///< [AI] Control/trigger for platform "left" movement.
	c_Rotate_Sound = 71,               ///< [AI] Sound trigger for platform/car rotation.
	c_PlatformLeft_Bitmap = 72,        ///< [AI] Bitmap for platform "left" arrow/button.
	c_Yellow_Ctl = 73,                 ///< [AI] UI control for yellow color.
	c_Yellow_Up_Bitmap = 74,           ///< [AI] "Up" (unpressed/highlighted) bitmap for yellow paint.
	c_Yellow_Down_Bitmap = 75,         ///< [AI] "Down" (pressed) bitmap for yellow paint.
	c_Red_Ctl = 76,                    ///< [AI] UI control for red color.
	c_Red_Up_Bitmap = 77,              ///< [AI] "Up" (unpressed/highlighted) bitmap for red paint.
	c_Red_Down_Bitmap = 78,            ///< [AI] "Down" (pressed) bitmap for red paint.
	c_Blue_Ctl = 79,                   ///< [AI] UI control for blue color.
	c_Blue_Up_Bitmap = 80,             ///< [AI] "Up" bitmap for blue paint.
	c_Blue_Down_Bitmap = 81,           ///< [AI] "Down" bitmap for blue paint.
	c_Green_Ctl = 82,                  ///< [AI] UI control for green color.
	c_Green_Up_Bitmap = 83,            ///< [AI] "Up" bitmap for green paint.
	c_Green_Down_Bitmap = 84,          ///< [AI] "Down" bitmap for green paint.
	c_Gray_Ctl = 85,                   ///< [AI] UI control for gray color.
	c_Gray_Up_Bitmap = 86,             ///< [AI] "Up" bitmap for gray paint.
	c_Gray_Down_Bitmap = 87,           ///< [AI] "Down" bitmap for gray paint.
	c_Black_Ctl = 88,                  ///< [AI] UI control for black color.
	c_Black_Up_Bitmap = 89,            ///< [AI] "Up" bitmap for black paint.
	c_Black_Down_Bitmap = 90,          ///< [AI] "Down" bitmap for black paint.
	c_Decals_Ctl = 91,                 ///< [AI] UI control for decal selection.
	c_Decal_State_0 = 92,              ///< [AI] Decal state selector 0 (no decal maybe).
	c_Decal_State_0_Bitmap = 93,       ///< [AI] Bitmap for decal state 0.
	c_Decal_State_1 = 94,              ///< [AI] Decal state selector 1.
	c_Decal_State_1_Bitmap = 95,       ///< [AI] Bitmap for decal state 1.
	c_Decal_Texture_1 = 96,            ///< [AI] Texture resource for decal 1.
	c_Decal_State_2 = 97,              ///< [AI] Decal state selector 2.
	c_Decal_State_2_Bitmap = 98,       ///< [AI] Bitmap for decal state 2.
	c_Decal_Texture_2 = 99,            ///< [AI] Texture resource for decal 2.
	c_Decal_State_3 = 100,             ///< [AI] Decal state selector 3.
	c_Decal_State_3_Bitmap = 101,      ///< [AI] Bitmap for decal state 3.
	c_Decal_Texture_3 = 102,           ///< [AI] Texture resource for decal 3.
	c_Decal_State_4 = 103,             ///< [AI] Decal state selector 4.
	c_Decal_State_4_Bitmap = 104,      ///< [AI] Bitmap for decal state 4.
	c_Decal_Texture_4 = 105,           ///< [AI] Texture resource for decal 4.
	c_Info_Up_Bitmap = 106,            ///< [AI] "Info" button in "up" (unpressed) state.
	c_Info_Down_Bitmap = 107,          ///< [AI] "Info" button in "down" (pressed) state.
	c_Exit_Up_Bitmap = 108,            ///< [AI] "Exit" button in "up" (unpressed) state.
	c_Exit_Down_Bitmap = 109,          ///< [AI] "Exit" button in "down" (pressed) state.
	c_Shelf_Sound = 110,               ///< [AI] Sound effect for shelf/toolbar movement.
	c_PlaceBrick_Sound = 111,          ///< [AI] Sound effect for placing a brick.
	c_GetBrick_Sound = 112,            ///< [AI] Sound effect for picking up a brick.
	c_Paint_Sound = 113,               ///< [AI] Sound effect for paint/color action.
	c_Decal_Sound = 114,               ///< [AI] Sound effect for applying a decal.
	c_Build_Animation = 115,           ///< [AI] Animation resource for generic building sequence.
	c_Build_Anim0 = 116,               ///< [AI] Animation for build sequence part 0.
	c_Build_Anim1 = 117,               ///< [AI] Animation for build sequence part 1.
	c_Build_Anim2 = 118,               ///< [AI] Animation for build sequence part 2.
	c_IGS001D3_Wav_500 = 119,          ///< [AI] Example WAV resource (possibly narration or VO).
	c_IGS001D3_Pho_500 = 120,          ///< [AI] PHO resource for lipsync (phoneme).
	c_igs001d3_0_sfx = 121,            ///< [AI] Indexed sound effect (0) for 001d3 sequence.
	c_igs001d3_1_sfx = 122,            ///< [AI] Indexed sound effect (1) for 001d3 sequence.
	c_igs001d3_2_sfx = 123,            ///< [AI] Indexed sound effect (2) for 001d3 sequence.
	c_igs001d3_3_sfx = 124,            ///< [AI] Indexed sound effect (3) for 001d3 sequence.
	c_igs001d3_4_sfx = 125,            ///< [AI] Indexed sound effect (4) for 001d3 sequence.
	c_igs001d3_5_sfx = 126,            ///< [AI] Indexed sound effect (5) for 001d3 sequence.
	c_igs001d3_6_sfx = 127,            ///< [AI] Indexed sound effect (6) for 001d3 sequence.
	c_igs001d3_7_sfx = 128,            ///< [AI] Indexed sound effect (7) for 001d3 sequence.
	c_igs001d3_8_sfx = 129,            ///< [AI] Indexed sound effect (8) for 001d3 sequence.
	c_igs001d3_9_sfx = 130,            ///< [AI] Indexed sound effect (9) for 001d3 sequence.
	c_igs001d3_10_sfx = 131,           ///< [AI] Indexed sound effect (10) for 001d3 sequence.
	c_igs001d3_11_sfx = 132,           ///< [AI] Indexed sound effect (11) for 001d3 sequence.
	c_igs001d3_12_sfx = 133,           ///< [AI] Indexed sound effect (12) for 001d3 sequence.
	c_igs001d3_13_sfx = 134,           ///< [AI] Indexed sound effect (13) for 001d3 sequence.
	c_igs001d3_14_sfx = 135,           ///< [AI] Indexed sound effect (14) for 001d3 sequence.
	c_igs001d3_15_sfx = 136,           ///< [AI] Indexed sound effect (15) for 001d3 sequence.
	c_igs001d3_16_sfx = 137,           ///< [AI] Indexed sound effect (16) for 001d3 sequence.
	c_igs001d3_17_sfx = 138,           ///< [AI] Indexed sound effect (17) for 001d3 sequence.
	c_igs001d3_18_sfx = 139,           ///< [AI] Indexed sound effect (18) for 001d3 sequence.
	c_igs001d3_19_sfx = 140,           ///< [AI] Indexed sound effect (19) for 001d3 sequence.
	c_igs001d3_Anim = 141,             ///< [AI] Animation resource for 001d3 sequence.
	c_IGSxx1D3_Wav_501 = 142,          ///< [AI] Example WAV resource (alternate sequence).
	c_IGSxx1D3_Pho_501 = 143,          ///< [AI] PHO resource for lipsync (alternate sequence).
	c_igsxx1d3_0_sfx = 144,            ///< [AI] Indexed sound effect (0) for xx1d3 sequence.
	c_igsxx1d3_1_sfx = 145,            ///< [AI] Indexed sound effect (1) for xx1d3 sequence.
	c_igsxx1d3_2_sfx = 146,            ///< [AI] Indexed sound effect (2) for xx1d3 sequence.
	c_igsxx1d3_Anim = 147,             ///< [AI] Animation resource for xx1d3 sequence.
	c_IGS002D3_Wav_502 = 148,          ///< [AI] WAV resource for 002d3 sequence.
	c_IGS002D3_Pho_502 = 149,          ///< [AI] PHO resource for 002d3 sequence.
	c_igs002d3_0_sfx = 150,            ///< [AI] Indexed sfx for 002d3 sequence.
	c_igs002d3_Anim = 151,             ///< [AI] Animation for 002d3 sequence.
	c_IGS003D3_Wav_503 = 152,          ///< [AI] WAV resource for 003d3 sequence.
	c_IGS003D3_Pho_503 = 153,          ///< [AI] PHO resource for 003d3 sequence.
	c_igs003d3_0_sfx = 154,            ///< [AI] Indexed sound effect (0) for 003d3 sequence.
	c_igs003d3_1_sfx = 155,            ///< [AI] Indexed sound effect (1) for 003d3 sequence.
	c_igs003d3_2_sfx = 156,            ///< [AI] Indexed sound effect (2) for 003d3 sequence.
	c_igs003d3_3_sfx = 157,            ///< [AI] Indexed sound effect (3) for 003d3 sequence.
	c_igs003d3_4_sfx = 158,            ///< [AI] Indexed sound effect (4) for 003d3 sequence.
	c_igs003d3_5_sfx = 159,            ///< [AI] Indexed sound effect (5) for 003d3 sequence.
	c_igs003d3_6_sfx = 160,            ///< [AI] Indexed sound effect (6) for 003d3 sequence.
	c_igs003d3_7_sfx = 161,            ///< [AI] Indexed sound effect (7) for 003d3 sequence.
	c_igs003d3_8_sfx = 162,            ///< [AI] Indexed sound effect (8) for 003d3 sequence.
	c_igs003d3_Anim = 163,             ///< [AI] Animation for 003d3 sequence.
	c_IGS004D3_Wav_504 = 164,          ///< [AI] WAV resource for 004d3 sequence.
	c_IGS004D3_Pho_504 = 165,          ///< [AI] PHO resource for 004d3 sequence.
	c_igs004d3_0_sfx = 166,            ///< [AI] Indexed sound effect (0) for 004d3 sequence.
	c_igs004d3_1_sfx = 167,            ///< [AI] Indexed sound effect (1) for 004d3 sequence.
	c_igs004d3_2_sfx = 168,            ///< [AI] Indexed sound effect (2) for 004d3 sequence.
	c_igs004d3_3_sfx = 169,            ///< [AI] Indexed sound effect (3) for 004d3 sequence.
	c_igs004d3_4_sfx = 170,            ///< [AI] Indexed sound effect (4) for 004d3 sequence.
	c_igs004d3_Anim = 171,             ///< [AI] Animation for 004d3 sequence.
	c_IGS005D3_Wav_505 = 172,          ///< [AI] WAV resource for 005d3 sequence.
	c_IGS005D3_Pho_505 = 173,          ///< [AI] PHO resource for 005d3 sequence.
	c_igs005d3_0_sfx = 174,            ///< [AI] Indexed sound effect (0) for 005d3 sequence.
	c_igs005d3_1_sfx = 175,            ///< [AI] Indexed sound effect (1) for 005d3 sequence.
	c_igs005d3_2_sfx = 176,            ///< [AI] Indexed sound effect (2) for 005d3 sequence.
	c_igs005d3_3_sfx = 177,            ///< [AI] Indexed sound effect (3) for 005d3 sequence.
	c_igs005d3_4_sfx = 178,            ///< [AI] Indexed sound effect (4) for 005d3 sequence.
	c_igs005d3_5_sfx = 179,            ///< [AI] Indexed sound effect (5) for 005d3 sequence.
	c_igs005d3_Anim = 180,             ///< [AI] Animation for 005d3 sequence.

	c_igs001d3_RunAnim = 500,          ///< [AI] Run animation for 001d3 sequence.
	c_igsxx1d3_RunAnim = 501,          ///< [AI] Run animation for xx1d3 sequence.
	c_igs002d3_RunAnim = 502,          ///< [AI] Run animation for 002d3 sequence.
	c_igs003d3_RunAnim = 503,          ///< [AI] Run animation for 003d3 sequence.
	c_igs004d3_RunAnim = 504,          ///< [AI] Run animation for 004d3 sequence.
	c_igs005d3_RunAnim = 505           ///< [AI] Run animation for 005d3 sequence.
};
} // namespace DunecarScript

#endif // DUNECAR_ACTIONS_H
