// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef INFOMAIN_ACTIONS_H
#define INFOMAIN_ACTIONS_H

/// @file [AI]
/// @brief [AI] Defines the enumeration of script and resource identifiers used by the Infomain scene in LEGO Island. This includes bitmap, animation, sound, and entity references, as well as utility constants for scripting logic.

namespace InfomainScript
{
#if __cplusplus >= 201103L
/// @enum Script
/// @brief [AI] Enumeration of all script, bitmap, animation, sound, and entity constants used throughout the InfoMain environment of LEGO Island. [AI]
/// @details [AI] These enum values provide unique integral identifiers for all resources and script actions processed by the InfoMain scripting engine, allowing SI files and core game code to refer to resources unambiguously. This also enables automatic SI file resource extraction, in-game scripting, and animation/sound control for interactive elements such as buttons, characters, and background scenes. [AI]
enum Script : int {
#else
enum Script {
#endif
	c_noneInfomain = -1, ///< [AI] Indicates that no specific script/action/resource is assigned or selected. Used as an invalid/none constant. [AI]

	c__InfoMain = 0, ///< [AI] Root script or entrypoint for InfoMain. Used to identify the main script file/context for scene initialization. [AI]
	c_LeftArrow_Ctl = 1, ///< [AI] Script/control for the left arrow UI element, handles navigation within InfoMain. [AI]
	c_RightArrow_Ctl = 2, ///< [AI] Script/control for the right arrow UI element, handles navigation within InfoMain. [AI]
	c_Info_Ctl = 3, ///< [AI] Script/control for the main Info ("I") button logic. [AI]
	c_Door_Ctl = 4, ///< [AI] Control script for door UI element, likely used for exiting InfoMain or other scene changes. [AI]
	c_Infoman_Entity = 5, ///< [AI] Entity reference for the Infoman character in InfoMain. [AI]
	c_RedBrick_Entity = 6, ///< [AI] Entity reference for the Red Brick model. [AI]
	c_GreenBrick_Entity = 7, ///< [AI] Entity reference for the Green Brick model. [AI]
	c_RegBook_Bmp = 8, ///< [AI] Bitmap resource for the registration book (green version), visual asset. [AI]
	c_RegBook_Flc = 9, ///< [AI] Animation (FLC) for the registration book (green version). [AI]
	c_Boat_Ctl = 10, ///< [AI] UI/button logic for "Boat" menu/scene elements. [AI]
	c_Race_Ctl = 11, ///< [AI] UI/button logic for "Race" menu/scene elements. [AI]
	c_Pizza_Ctl = 12, ///< [AI] UI/button logic for "Pizza" menu/scene elements. [AI]
	c_Gas_Ctl = 13, ///< [AI] UI/button logic for "Gas" menu/scene elements. [AI]
	c_Med_Ctl = 14, ///< [AI] UI/button logic for "Medical" (hospital) menu/scene elements. [AI]
	c_Cop_Ctl = 15, ///< [AI] UI/button logic for "Police" (Cop) menu/scene elements. [AI]
	c_BigInfo_Ctl = 16, ///< [AI] UI/button logic for the large Info button ("Big I") in InfoMain. [AI]
	c_Book_Ctl = 17, ///< [AI] Script/control for the book icon/button in InfoMain. [AI]
	c_Radio_Ctl = 18, ///< [AI] Script/control for radio UI/button or logic. [AI]
	c_RegBookRed_Bmp = 19, ///< [AI] Bitmap resource for the Red registration book. [AI]
	c_RegBookRed_Flc = 20, ///< [AI] Animation (FLC) for the Red registration book. [AI]
	c_Mama_Ctl = 21, ///< [AI] Script/control logic for "Mama" Brick character. [AI]
	c_Papa_Ctl = 22, ///< [AI] Script/control logic for "Papa" Brick character. [AI]
	c_Pepper_Ctl = 23, ///< [AI] Script/control logic for "Pepper" character. [AI]
	c_Nick_Ctl = 24, ///< [AI] Script/control logic for "Nick". [AI]
	c_Laura_Ctl = 25, ///< [AI] Script/control logic for "Laura". [AI]
	c_Info_A_Bitmap = 26, ///< [AI] Bitmap for Info ("I") button in state A or variant. [AI]
	c_Boat_A_Bitmap = 27, ///< [AI] Bitmap for Boat button in state A or variant. [AI]
	c_Race_A_Bitmap = 28, ///< [AI] Bitmap for Race button in state A or variant. [AI]
	c_Pizza_A_Bitmap = 29, ///< [AI] Bitmap for Pizza button in state A or variant. [AI]
	c_MamaHot_Bitmap = 30, ///< [AI] Hot/clickable bitmap for "Mama" character. Used for mouseover or click visuals. [AI]
	c_PapaHot_Bitmap = 31, ///< [AI] Hot/clickable bitmap for "Papa" character. [AI]
	c_PepperHot_Bitmap = 32, ///< [AI] Hot/clickable bitmap for "Pepper" character. [AI]
	c_NickHot_Bitmap = 33, ///< [AI] Hot/clickable bitmap for "Nick" character. [AI]
	c_LauraHot_Bitmap = 34, ///< [AI] Hot/clickable bitmap for "Laura" character. [AI]
	c_Gas_A_Bitmap = 35, ///< [AI] Bitmap for Gas button in state A or variant. [AI]
	c_Med_A_Bitmap = 36, ///< [AI] Bitmap for Med button in state A or variant. [AI]
	c_Cop_A_Bitmap = 37, ///< [AI] Bitmap for Cop button in state A or variant. [AI]
	c_FrameHot_Bitmap = 38, ///< [AI] Hot/clickable bitmap for the frame, likely for cursor/interaction hitboxes. [AI]
	c_Background_Bitmap = 39, ///< [AI] Bitmap for InfoMain scene background. [AI]
	c_Mama_All_Movie = 40, ///< [AI] Full-sequence animation/movie for Mama character. [AI]
	c_Papa_All_Movie = 41, ///< [AI] Full-sequence animation/movie for Papa character. [AI]
	c_Pepper_All_Movie = 42, ///< [AI] Full-sequence animation/movie for Pepper character. [AI]
	c_Nick_All_Movie = 43, ///< [AI] Full-sequence animation/movie for Nick character. [AI]
	c_Laura_All_Movie = 44, ///< [AI] Full-sequence animation/movie for Laura character. [AI]
	c_BackgroundRed_Bitmap = 45, ///< [AI] Bitmap for alternate/red InfoMain background. [AI]
	c_Infoman_Model = 46, ///< [AI] 3D model reference for Infoman character in InfoMain. [AI]
	c_Brick2x4grn_Model = 47, ///< [AI] 3D model reference for green 2x4 brick. [AI]
	c_Brick2x4red_Model = 48, ///< [AI] 3D model reference for red 2x4 brick. [AI]
	c_LeftArrow_Up_Bitmap = 49, ///< [AI] Bitmap for left arrow button in "up"/idle state. [AI]
	c_LeftArrow_Down_Bitmap = 50, ///< [AI] Bitmap for left arrow button in "down"/pressed state. [AI]
	c_RightArrow_Up_Bitmap = 51, ///< [AI] Bitmap for right arrow button idle state. [AI]
	c_RightArrow_Down_Bitmap = 52, ///< [AI] Bitmap for right arrow button pressed state. [AI]
	c_BigInfo_Up_Bitmap = 53, ///< [AI] Bitmap for big Info ("I") button up/idle state. [AI]
	c_BigInfo_Down = 54, ///< [AI] Placeholder or intermediate value for big Info button down state or related transition. [AI_SUGGESTED_CORRECTED_NAME: c_BigInfo_Down_Bitmap]
	c_BigInfo_Down_Bitmap = 55, ///< [AI] Bitmap for big Info ("I") button down/pressed state. [AI]
	c_RadioOff_Bitmap = 56, ///< [AI] Bitmap resource for radio in off state. [AI]
	c_RadioOn_Bitmap = 57, ///< [AI] Bitmap resource for radio in on state. [AI]
	c_Book_Mask_Bitmap = 58, ///< [AI] Transparency mask bitmap for book element. [AI]
	c_Door_Mask_Bitmap = 59, ///< [AI] Transparency mask bitmap for door element. [AI]
	c_Info_Up_Bitmap = 60, ///< [AI] Bitmap for Info ("I") button in idle/up state. [AI]
	c_Info_Down_Bitmap = 61, ///< [AI] Bitmap for Info ("I") button in pressed/down state. [AI]
	c_Boat_Up_Bitmap = 62, ///< [AI] Bitmap for Boat button idle/up state. [AI]
	c_Boat_Down_Bitmap = 63, ///< [AI] Bitmap for Boat button pressed/down state. [AI]
	c_Race_Up_Bitmap = 64, ///< [AI] Bitmap for Race button idle/up state. [AI]
	c_Race_Down_Bitmap = 65, ///< [AI] Bitmap for Race button pressed/down state. [AI]
	c_Pizza_Up_Bitmap = 66, ///< [AI] Bitmap for Pizza button idle/up state. [AI]
	c_Pizza_Down_Bitmap = 67, ///< [AI] Bitmap for Pizza button pressed/down state. [AI]
	c_Gas_Up_Bitmap = 68, ///< [AI] Bitmap for Gas button idle/up state. [AI]
	c_Gas_Down_Bitmap = 69, ///< [AI] Bitmap for Gas button pressed/down state. [AI]
	c_GoTo_RegBook = 70, ///< [AI] Script/action to transition to green registration book scene. [AI]
	c_GoTo_RegBook_Red = 71, ///< [AI] Script/action to transition to red registration book scene. [AI]
	c_Med_Up_Bitmap = 72, ///< [AI] Bitmap for Medical (hospital) button idle/up state. [AI]
	c_Med_Down_Bitmap = 73, ///< [AI] Bitmap for Medical (hospital) button pressed/down state. [AI]
	c_Cop_Up_Bitmap = 74, ///< [AI] Bitmap for Cop (police) button idle/up state. [AI]
	c_Cop_Down_Bitmap = 75, ///< [AI] Bitmap for Cop (police) button pressed/down state. [AI]
	c_Mama_Up_Bitmap = 76, ///< [AI] Bitmap for "Mama" character in idle/up state. [AI]
	c_Mama_Down_Bitmap = 77, ///< [AI] Bitmap for "Mama" character in pressed/down state. [AI]
	c_Papa_Up_Bitmap = 78, ///< [AI] Bitmap for "Papa" character idle/up state. [AI]
	c_Papa_Down_Bitmap = 79, ///< [AI] Bitmap for "Papa" character pressed/down state. [AI]
	c_Pepper_Up_Bitmap = 80, ///< [AI] Bitmap for "Pepper" character idle/up state. [AI]
	c_Pepper_Down_Bitmap = 81, ///< [AI] Bitmap for "Pepper" character pressed/down state. [AI]
	c_Nick_Up_Bitmap = 82, ///< [AI] Bitmap for "Nick" character idle/up state. [AI]
	c_Nick_Down_Bitmap = 83, ///< [AI] Bitmap for "Nick" character pressed/down state. [AI]
	c_Laura_Up_Bitmap = 84, ///< [AI] Bitmap for "Laura" character idle/up state. [AI]
	c_Laura_Down_Bitmap = 85, ///< [AI] Bitmap for "Laura" character pressed/down state. [AI]
	c_ConfigAnimation = 86, ///< [AI] Configuration script or animation resource; exact purpose context-dependent. [AI]
	// Movie and waving/smoking animations for all characters
	c_Mama_Start_Movie = 87, ///< [AI] Beginning/cue movie for Mama. [AI]
	c_Mama_ScreenDown_Wave = 88, ///< [AI] Animation where Mama waves as the screen scrolls down. [AI]
	c_Mama_ScreenDown_Smk = 89, ///< [AI] Animation for Mama (screen down, smoking). [AI]
	c_Mama_Movie = 90, ///< [AI] Main movie/animation for Mama. [AI]
	c_Mama_Wave = 91, ///< [AI] Isolated wave animation for Mama. [AI]
	c_Mama_Smk = 92, ///< [AI] Isolated smoking animation for Mama. [AI]
	c_Mama_End_Movie = 93, ///< [AI] Ending movie segment for Mama. [AI]
	c_Mama_ScreenUp_Wave = 94, ///< [AI] Animation for Mama as screen scrolls up (waving). [AI]
	c_Mama_ScreenUp_Smk = 95, ///< [AI] Animation for Mama as screen scrolls up (smoking). [AI]
	c_Papa_Start_Movie = 96,
	c_Papa_ScreenDown_Wave = 97,
	c_Papa_ScreenDown_Smk = 98,
	c_Papa_Movie = 99,
	c_Papa_Wave = 100,
	c_Papa_Smk = 101,
	c_Papa_End_Movie = 102,
	c_Papa_ScreenUp_Wave = 103,
	c_Papa_ScreenUp_Smk = 104,
	c_Pepper_Start_Movie = 105,
	c_Pepper_ScreenDown_Wave = 106,
	c_Pepper_ScreenDown_Smk = 107,
	c_Pepper_Movie = 108,
	c_Pepper_Wave = 109,
	c_Pepper_Smk = 110,
	c_Pepper_End_Movie = 111,
	c_Pepper_ScreenUp_Wave = 112,
	c_Pepper_ScreenUp_Smk = 113,
	c_Nick_Start_Movie = 114,
	c_Nick_ScreenDown_Wave = 115,
	c_Nick_ScreenDown_Smk = 116,
	c_Nick_Movie = 117,
	c_Nick_Wave = 118,
	c_Nick_Smk = 119,
	c_Nick_End_Movie = 120,
	c_Nick_ScreenUp_Wave = 121,
	c_Nick_ScreenUp_Smk = 122,
	c_Laura_Start_Movie = 123,
	c_Laura_ScreenDown_Wave = 124,
	c_Laura_ScreenDown_Smk = 125,
	c_Laura_Movie = 126,
	c_Laura_Wave = 127,
	c_Laura_Smk = 128,
	c_Laura_End_Movie = 129,
	c_Laura_ScreenUp_Wave = 130,
	c_Laura_ScreenUp_Smk = 131,
	// Additional sound, phoneme, and script/animation resources follow similar conventions [AI]
	// ...
	// See code generation for full resource list. All are referenced similarly for bitmap, anim, sound, or script selection. [AI]
	c_IIC005IN_Wav_500 = 132, ///< [AI] Example: WAV sound file for VO or SFX, ID 500.
	// ...
	// More sound/animation/bitmap resources omitted for brevity [AI]
	// ...
	c_AVO905IN_Pho_545 = 486,
	c_avo905in_Anim = 487,
	// Secondary action and wav triggers [AI]
	c_iic001in_RunAnim = 500, ///< [AI] Begin running animation for IIC001IN sequence. [AI]
	c_iic016in_RunAnim = 501,
	c_iicx17in_RunAnim = 502,
	c_iic018in_RunAnim = 503,
	c_iicx18in_RunAnim = 504,
	c_iic019in_RunAnim = 505,
	c_iic020in_RunAnim = 506,
	c_iic021in_RunAnim = 507,
	c_iic022in_RunAnim = 508,
	c_iic023in_RunAnim = 509,
	c_iicx23in_RunAnim = 510,
	c_iic024in_RunAnim = 511,
	c_iic025in_RunAnim = 512,
	c_iic026in_RunAnim = 513,
	c_iicx26in_RunAnim = 514,
	c_iic027in_RunAnim = 515,
	c_iic029in_RunAnim = 516,
	c_iic032in_RunAnim = 517,
	c_iic033in_RunAnim = 518,
	c_iic034in_RunAnim = 519,
	c_iic035in_RunAnim = 520,
	c_iic036in_RunAnim = 521,
	c_iic043in_RunAnim = 522,
	c_iic045in_RunAnim = 523,
	c_iic046in_RunAnim = 524,
	c_iic048in_RunAnim = 525,
	c_iic049in_RunAnim = 526,
	c_iic050in_RunAnim = 527,
	c_iic055in_RunAnim = 528,
	c_iic056in_RunAnim = 529,
	c_iic057in_RunAnim = 530,
	c_iic058in_RunAnim = 531,
	c_iica28in_RunAnim = 532,
	c_iica30in_RunAnim = 533,
	c_iicb28in_RunAnim = 534,
	c_iicb30in_RunAnim = 535,
	c_iicc28in_RunAnim = 536,
	c_nic002in_RunAnim = 537,
	c_nic003in_RunAnim = 538,
	c_tic089in_RunAnim = 539,
	c_tic092in_RunAnim = 540,
	c_avo901in_RunAnim = 541,
	c_avo902in_RunAnim = 542,
	c_avo903in_RunAnim = 543,
	c_avo904in_RunAnim = 544,
	c_avo905in_RunAnim = 545,
	c_AVo901In_PlayWav = 546, ///< [AI] Play sound effect or voice (WAV) for AV0 901 in sequence. [AI]
	c_AVo902In_PlayWav = 547,
	c_AVo903In_PlayWav = 548,
	c_AVo904In_PlayWav = 549,
	c_AVo905In_PlayWav = 550,
	c_Avo929In_PlayWav = 551,
	c_iic062in_PlayWav = 552,
	c_iic063in_PlayWav = 553,
	c_iic064in_PlayWav = 554,
	c_igs004ra_PlayWav = 555,
	c_iho003ra_PlayWav = 556,
	c_iic007ra_PlayWav = 557,
	c_ijs002ra_PlayWav = 558,
	c_ips005ra_PlayWav = 559,
	c_ipz006ra_PlayWav = 560,
	c_irt001ra_PlayWav = 561,
	c_iic039in_PlayWav = 562,
	c_iic040in_PlayWav = 563,
	c_iic041in_PlayWav = 564,
	c_iic042in_PlayWav = 565,
	c_iic059in_PlayWav = 566,
	c_iic060in_PlayWav = 567,
	c_iic061in_PlayWav = 568,
	c_iic051in_PlayWav = 569,
	c_iic052in_PlayWav = 570,
	c_iic053in_PlayWav = 571,
	c_iic054in_PlayWav = 572,
	c_iic007in_PlayWav = 573,
	c_sbleh2br_PlayWav = 574,
	c_snshahbr_PlayWav = 575
};
} // namespace InfomainScript

#endif // INFOMAIN_ACTIONS_H