// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef JUKEBOX_ACTIONS_H
#define JUKEBOX_ACTIONS_H

/// @namespace JukeboxScript [AI]
/// @brief [AI] Contains an enumeration of all scripts used for the Jukebox system in LEGO Island.
/// @details [AI] This namespace holds identifiers for audio and movie scripts that can be played or referenced by the Jukebox system.
namespace JukeboxScript
{
#if __cplusplus >= 201103L
/// @enum Script [AI]
/// @brief [AI] Enumerates all possible script identifiers for the Jukebox.
/// @details [AI] Each value corresponds to a different music or movie track that can be triggered by the Jukebox or used in different areas/events across LEGO Island.
enum Script : int {
#else
/// @enum Script [AI]
/// @brief [AI] Enumerates all possible script identifiers for the Jukebox.
/// @details [AI] Each value corresponds to a different music or movie track that can be triggered by the Jukebox or used in different areas/events across LEGO Island.
enum Script {
#endif
	c_noneJukebox = -1, ///< [AI] Special value representing that no Jukebox script is selected or active.

	c_MusicTheme1 = 0, ///< [AI] Main theme music, variant 1.
	c_MusicTheme3 = 1, ///< [AI] Main theme music, variant 3.
	c_Act2Cave = 2, ///< [AI] Music track for Act 2 Cave scene.
	c_BrickstrChase = 3, ///< [AI] Music for the Brickster Chase sequence.
	c_BrickHunt = 4, ///< [AI] Music for Brick Hunt mission.
	c_ResidentalArea_Music = 5, ///< [AI] Music for the residential area environment.
	c_BeachBlvd_Music = 6, ///< [AI] Music for Beach Boulevard.
	c_Cave_Music = 7, ///< [AI] Music for cave locations.
	c_CentralRoads_Music = 8, ///< [AI] Background music for LEGO Island central roads.
	c_Jail_Music = 9, ///< [AI] Background music for the jail area.
	c_Hospital_Music = 10, ///< [AI] Background music for the hospital.
	c_InformationCenter_Music = 11, ///< [AI] Background music for the information center.
	c_PoliceStation_Music = 12, ///< [AI] Music played inside or near the police station.
	c_Park_Music = 13, ///< [AI] Music for park environments.
	c_CentralNorthRoad_Music = 14, ///< [AI] Music for central northern roads.
	c_GarageArea_Music = 15, ///< [AI] Music in the garage or vehicle area.
	c_RaceTrackRoad_Music = 16, ///< [AI] Music for the racetrack roads.
	c_Beach_Music = 17, ///< [AI] Ambient/area music for the beach.
	c_Quiet_Audio = 18, ///< [AI] Quiet/ambient audio track, likely used to mute or dampen music.
	c_JetskiRace_Music = 19, ///< [AI] Music for the Jetski race event.
	c_Act3Music = 20, ///< [AI] Act 3 background music.
	c_sns002ra_Audio = 21, ///< [AI] Specific alternate background/ambience used in an area or event. (Name based on asset codes.)
	c_sns001ja_Audio = 22, ///< [AI] Special music/ambience, asset code derived.
	c_snsc01js_Audio = 23, ///< [AI] Special area/event audio track, asset code derived.
	c_snsb01js_Audio = 24, ///< [AI] Asset-coded audio/event track.
	c_snsa01js_Audio = 25, ///< [AI] Asset-coded audio/event track.
	c_sns009ra_Audio = 26, ///< [AI] Asset-coded audio/event track.
	c_ham035ra_Audio = 27, ///< [AI] Asset-coded audio/event track.
	c_ham039ra_Audio = 28, ///< [AI] Asset-coded audio/event track.
	c_sns005ra_Audio = 29, ///< [AI] Asset-coded audio/event track.
	c_sns078pa_Audio = 30, ///< [AI] Asset-coded audio/event track.
	c_ham036ra_Audio = 31, ///< [AI] Asset-coded audio/event track.
	c_sns006ra_Audio = 32, ///< [AI] Asset-coded audio/event track.
	c_sns013ra_Audio = 33, ///< [AI] Asset-coded audio/event track.
	c_sns004ra_Audio = 34, ///< [AI] Asset-coded audio/event track.
	c_sns079pa_Audio = 35, ///< [AI] Asset-coded audio/event track.
	c_sns007ra_Audio = 36, ///< [AI] Asset-coded audio/event track.
	c_sns008ra_Audio = 37, ///< [AI] Asset-coded audio/event track.
	c_hpz037ma_Audio = 38, ///< [AI] Asset-coded audio/event track.
	c_sns003ra_Audio = 39, ///< [AI] Asset-coded audio/event track.
	c_sns010ra_Audio = 40, ///< [AI] Asset-coded audio/event track.
	c_Radio1_Music = 41, ///< [AI] First of several radio tracks available via the radio.
	c_Radio2_Music = 42, ///< [AI] Second radio track.
	c_Radio3_Music = 43, ///< [AI] Third radio track.
	c_Radio4_Music = 44, ///< [AI] Fourth radio track.
	c_Radio5_Music = 45, ///< [AI] Fifth radio track.
	c_Radio6_Music = 46, ///< [AI] Sixth radio track.
	c_HelicopterBuild_Movie = 47, ///< [AI] Movie/cutscene that plays during the helicopter build.
	c_HelicopterBuild_Music = 48, ///< [AI] Music used for the helicopter build event.
	c_DuneCarBuild_Movie = 49, ///< [AI] Movie/cutscene for Dune Car build sequence.
	c_DuneCarBuild_Music = 50, ///< [AI] Music used for the Dune Car build.
	c_JetskiBuild_Movie = 51, ///< [AI] Movie/cutscene for Jetski build sequence.
	c_JetskiBuild_Music = 52, ///< [AI] Music for the Jetski build event.
	c_RaceCarBuild_Movie = 53, ///< [AI] Movie/cutscene for Race Car build sequence.
	c_RaceCarBuild_Music = 54, ///< [AI] Music for the Race Car build.
	c_JBMusic1 = 55, ///< [AI] Jukebox miscellaneous music 1.
	c_JBMusic2 = 56, ///< [AI] Jukebox miscellaneous music 2.
	c_JBMusic3 = 57, ///< [AI] Jukebox miscellaneous music 3.
	c_JBMusic4 = 58, ///< [AI] Jukebox miscellaneous music 4.
	c_JBMusic5 = 59, ///< [AI] Jukebox miscellaneous music 5.
	c_JBMusic6 = 60, ///< [AI] Jukebox miscellaneous music 6.
	c_InfoCenter_3rd_Floor_Music = 61, ///< [AI] Music for the information center's third floor.
	c_Elevator_Music = 62, ///< [AI] Music for elevator sequences.
	c_PizzaMission_Music = 63, ///< [AI] Music for the pizza mission event/sequence.
	c_HelicopterBuild_Flic = 64, ///< [AI] FLIC-format animation for the helicopter build.
	c_DuneCarBuild_Flic = 65, ///< [AI] FLIC-format animation for the dune car build.
	c_JetskiBuild_Flic = 66, ///< [AI] FLIC-format animation for the jetski build.
	c_RaceCarBuild_Flic = 67 ///< [AI] FLIC-format animation for the racecar build.
};
} // namespace JukeboxScript

#endif // JUKEBOX_ACTIONS_H